# Generated by Django 3.2 on 2021-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_ingradient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
