# Generated by Django 3.2 on 2021-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_step_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.TextField(),
        ),
    ]
